name: Build and Release Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (格式：v1.0.0)"
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.tag }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ inputs.tag }}
        name: Release ${{ inputs.tag }}
        body: |
          Docker 镜像构建版本：${{ inputs.tag }}
          镜像地址：`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.tag }}`
        draft: false
        prerelease: false
