name: 手动更新外部 Repo 最新 Tag 到 temp/tag.md

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  update-tag-file:
    runs-on: ubuntu-latest

    steps:
      # ========== 1. Checkout 仓库 ==========
      - name: Checkout 仓库
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # ========== 2. 初始化 temp 目录 ==========
      - name: 创建 temp 目录
        run: mkdir -p temp

      # ========== 3. 获取外部仓库最新 Tag ==========
      - name: 获取 IamFurina/SPlayer 最新版本号
        id: get_latest_tag
        run: |
          LATEST_TAG=$(git ls-remote --tags https://github.com/IamFurina/SPlayer.git \
            | awk '{print $2}' \
            | sed 's@refs/tags/@@' \
            | grep -E '^[0-9]' \
            | sort -V \
            | tail -n1)
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      # ========== 4. 写入 temp/tag.md ==========
      - name: 写入最新 Tag 到 temp/tag.md
        run: |
          echo "${{ steps.get_latest_tag.outputs.latest_tag }}" > temp/tag.md

      # ========== 5. 提交并推送 temp/tag.md（方式二：手动引用 GITHUB_TOKEN） ==========
      - name: 提交并推送 temp/tag.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add temp/tag.md
          git commit -m "chore: 更新 temp/tag.md -> ${{ steps.get_latest_tag.outputs.latest_tag }}"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
